# Custom Language File for Launcher Customizer

[ejs.app]
title = "CraftGame.net // Minecraft"
loginUrl = "http://craftgame.net/launcher/auth"

[ejs.landing]
mediaWebsiteURL = "http://craftgame.net/"
mediaGitHubURL = "http://craftgame.net/"
mediaDiscordURL = "http://link.craftgame.net/cgnds"
