[ejs.landing]
updateAvailableTooltip = "Доступно обновление"
usernamePlaceholder = "Логин"
usernameEditButton = "Редактировать"
settingsTooltip = "Настройки"
serverStatus = "Сервер"
serverStatusPlaceholder = "Оффлайн"
newsButton = "Новости"
launchButton = "Играть"
launchButtonPlaceholder = "&#8226; Сервер не выбран"
launchDetails = "Пожалуйста, подождите.."
newsNavigationStatus = "{currentPage} из {totalPages}"
newsErrorLoadSpan = "Загрузка новостей.."
newsErrorFailedSpan = "Не удалось загрузить новости"
newsErrorRetryButton = "Попробуйте позже"
newsErrorNoneSpan = "Новостей нет"

[ejs.login]
loginCancelText = "Отменить"
loginSubheader = "Логин minecraft"
loginEmailError = "* Некорректное значение"
loginEmailPlaceholder = "Email или логин"
loginPasswordError = "* Обязательно"
loginPasswordPlaceholder = "Пароль"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Забыли пароль?"
loginRememberMeText = "Запомнить меня?"
loginButtonText = "Логин"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Нет аккаунта?"
loginPasswordDisclaimer1 = "Ваш пароль отправляется непосредственно в Mojang и никогда не сохраняется."
loginPasswordDisclaimer2 = "{appName} не связан с Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "CraftGame.net"
loginWithWebsite = "Авторизация"
cancelButton = "Отмена"

[ejs.overlay]
serverSelectHeader = "Сервера"
serverSelectConfirm = "Выбрать"
serverSelectCancel = "Отмена"
accountSelectHeader = "Выбрать аккаунт"
accountSelectConfirm = "Выбрать"
accountSelectCancel = "Отмена"

[ejs.settings]
navHeaderText = "Настройки"
navAccount = "Профиль"
navMinecraft = "Minecraft"
navMods = "Моды"
navJava = "Java"
navLauncher = "Лаунчер"
navAbout = "О приложении"
navUpdates = "Обновления"
navDone = "Сохранить"
tabAccountHeaderText = "Профиль"
tabAccountHeaderDesc = "Добавьте новые аккаунты или управляйте существующими." # todo: remove
microsoftAccount = "Microsoft" #todo remove
addMicrosoftAccount = "+ Добавить аккаунт Microsoft" # todo rmove
mojangAccount = "Mojang" # todo rmove
addMojangAccount = "+ Добавить аккаунт Mojang" # todo rmove
minecraftTabHeaderText = "Minecraft"
minecraftTabHeaderDesc = "Опции, связанные с запуском игры." # todo rmove
gameResolutionTitle = "Размер окна игры"
launchFullscreenTitle = "Полноэкранный режим"
autoConnectTitle = "Автоматически подключаться к серверу" # todo rmove
launchDetachedTitle = "Запуск процесса игры отделенно от лаунчера." # todo rmove
launchDetachedDesc = "Если игра не отделена, закрытие лаунчера также закроет игру." # todo rmove
tabModsHeaderText = "Настройки модов"
tabModsHeaderDesc = "Включите или отключите моды."
switchServerButton = "Переключить"
requiredMods = "Обязательные моды"
optionalMods = "Дополнительные моды"
dropinMods = "Моды-добавки"
addMods = "Добавить моды"
dropinRefreshNote = "(F5 для обновления)"
shaderpacks = "Шейдерпаки"
shaderpackDesc = "Включите или отключите шейдеры. Обратите внимание, что шейдеры будут работать плавно только на мощных системах. Вы можете добавить собственные паки здесь."
selectShaderpack = "Выбрать шейдерпак"
tabJavaHeaderText = "Настройки Java"
tabJavaHeaderDesc = "Управление конфигурацией Java (для продвинутых)."
memoryTitle = "Память"
maxRAM = "Максимальная память"
minRAM = "Минимальная память"
memoryDesc = "Рекомендуемый минимум оперативной памяти - 3 гигабайта. Установка минимального и максимального значений на одно и то же значение может снизить задержки."
memoryTotalTitle = "Всего"
memoryAvailableTitle = "Доступно"
javaExecutableTitle = "Исполняемый файл Java"
javaExecSelDialogTitle = "Выберите исполняемый файл Java"
javaExecSelButtonText = "Выбрать файл"
javaExecDesc = "Исполняемый файл Java проверяется перед запуском игры."
javaPathDesc = "Путь должен заканчиваться на <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Дополнительные параметры JVM"
jvmOptsDesc = "Параметры, передаваемые JVM во время выполнения. <em>-Xms</em> и <em>-Xmx</em> не должны включаться."
launcherTabHeaderText = "Настройки лаунчера"
launcherTabHeaderDesc = "Опции, связанные с самим лаунчером."
allowPrereleaseTitle = "Разрешить предварительные обновления."
allowPrereleaseDesc = "Предварительные версии включают новые функции, которые могут быть не полностью протестированы или интегрированы.<br>Это всегда будет так, если вы используете предварительную версию."
dataDirectoryTitle = "Каталог данных"
selectDataDirectory = "Выберите каталог данных"
chooseFolder = "Выбрать папку"
dataDirectoryDesc = "Все файлы игры и локальные установки Java будут храниться в каталоге данных.<br>Снимки экрана и сохранения мира хранятся в папке экземпляра для соответствующей конфигурации сервера."
aboutTabHeaderText = "О приложении"
aboutTabHeaderDesc = "Просмотр информации и заметок к текущей версии."
aboutTitle = "{appName}"
stableRelease = "Стабильный релиз"
versionText = "Версия "
sourceGithub = "Исходный код (GitHub)"
support = "Поддержка"
originalSource = "Оригинальный исходный код"
devToolsConsole = "Консоль инструментов разработчика"
releaseNotes = "Примечания к релизу"
changelog = "История изменений"
noReleaseNotes = "Нет заметок о релизе"
viewReleaseNotes = "Просмотреть заметки о релизе на GitHub"
launcherUpdatesHeaderText = "Обновления лаунчера"
launcherUpdatesHeaderDesc = "Загрузка, установка и просмотр обновлений для лаунчера."
checkForUpdates = "Проверить наличие обновлений"
whatsNew = "Что нового"
updateReleaseNotes = "Обновить заметки о релизе"

[ejs.waiting]
waitingText = "Ожидание авторизации..."

[js.discord]
waiting = "Ожидание клиента.."
state = "Сервер: {shortId}"

[js.index]
microsoftLoginTitle = "Вход в Microsoft"
microsoftLogoutTitle = "Выход из Microsoft"

[js.login]
login = "ВХОД"
loggingIn = "ВХОД..."
success = "УСПЕШНО"
tryAgain = "Попробуйте ещё раз"

[js.login.error]
invalidValue = "* Некорректное значение"
requiredValue = "* Обязательно"

[js.login.error.unknown]
title = "Неизвестная ошибка во время входа"
desc = "Произошла неизвестная ошибка. Пожалуйста, проверьте консоль для получения дополнительной информации."

[js.landing.launch]
pleaseWait = "Пожалуйста, подождите.."
failureTitle = "Ошибка при запуске"
failureText = "Для получения дополнительной информации обратитесь к консоли (CTRL + Shift + i)."
okay = "ОК"

[js.landing.selectedAccount]
noAccountSelected = "Аккаунт не выбран"

[js.landing.selectedServer]
noSelection = "Сервер не выбран"
loading = "Загрузка.."

[js.landing.serverStatus]
server = "Сервер"
offline = "Оффлайн"
players = "Игроков"

[js.landing.systemScan]
checking = "Проверка системной информации.."
noCompatibleJava = "Не найдена совместимая<br>установка Java"
installJavaMessage = "Чтобы запустить Minecraft, вам понадобится 64-разрядная установка Java {major}. Хотите, чтобы мы установили копию?"
installJava = "Установить Java"
installJavaManually = "Установить вручную"
javaDownloadPrepare = "Подготовка к загрузке Java.."
javaDownloadFailureTitle = "Ошибка при загрузке Java"
javaDownloadFailureText = "Для получения дополнительной информации обратитесь к консоли (CTRL + Shift + i)."
javaRequired = "Для запуска требуется Java"
javaRequiredMessage = 'Для запуска необходима действительная 64-разрядная установка Java {major}.<br><br>Пожалуйста, ознакомьтесь с нашим <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Руководством по управлению Java</a> для получения инструкций по установке Java вручную.'
javaRequiredDismiss = "Понятно"
javaRequiredCancel = "Назад"

[js.landing.downloadJava]
findJdkFailure = "Не удалось найти дистрибутив OpenJDK."
javaDownloadCorruptedError = "Загруженный JDK имеет неверную хэш-сумму, файл может быть поврежден."
extractingJava = "Распаковка Java"
javaInstalled = "Java установлена!"

[js.landing.dlAsync]
loadingServerInfo = "Загрузка информации о сервере.."
fatalError = "Фатальная ошибка"
unableToLoadDistributionIndex = "Не удалось загрузить копию индекса дистрибуции. Для получения дополнительной информации обратитесь к консоли (CTRL + Shift + i)."
pleaseWait = "Пожалуйста, подождите.."
errorDuringLaunchTitle = "Ошибка при запуске"
seeConsoleForDetails = "Для получения дополнительной информации обратитесь к консоли (CTRL + Shift + i)."
validatingFileIntegrity = "Проверка целостности файлов.."
errorDuringFileVerificationTitle = "Ошибка при проверке файла"
downloadingFiles = "Загрузка файлов.."
errorDuringFileDownloadTitle = "Ошибка при загрузке файла"
preparingToLaunch = "Подготовка к запуску.."
launchingGame = "Запуск игры.."
launchWrapperNotDownloaded = "Основной файл, LaunchWrapper, не удалось правильно загрузить. В результате игра не может быть запущена.<br><br>Чтобы исправить эту проблему, временно отключите антивирусное программное обеспечение и повторите попытку запуска игры.<br><br>Если у вас есть время, пожалуйста, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">сообщите о проблеме</a> и дайте нам знать, каким антивирусным программным обеспечением вы пользуетесь. Мы свяжемся с ними и попробуем уладить ситуацию."
doneEnjoyServer = "Готово. Наслаждайтесь сервером!"
checkConsoleForDetails = "Пожалуйста, проверьте консоль (CTRL + Shift + i) для получения дополнительной информации."

[js.landing.news]
checking = "Проверка новостей"

[js.landing.discord]
loading = "Загрузка игры.."
joining = "Плаваем в Вестерос!"
joined = "Исследуем королевство!"

[js.overlay]
dismiss = "Закрыть"

[js.settings.fileSelectors]
executables = "Исполняемые файлы"
allFiles = "Все файлы"

[js.settings.mstfLogin]
errorTitle = "Что-то пошло не так"
errorMessage = "Не удалось аутентифицировать вашу учетную запись Microsoft. Пожалуйста, попробуйте еще раз."
okButton = "ОК"

[js.settings.mstfLogout]
errorTitle = "Что-то пошло не так"
errorMessage = "Не удалось выйти из учетной записи Microsoft. Пожалуйста, попробуйте еще раз."
okButton = "ОК"

[js.settings.authAccountSelect]
selectButton = "Выбрать аккаунт"
selectedButton = "Выбран аккаунт ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Предупреждение<br>Это ваш последний аккаунт"
lastAccountWarningMessage = "Для использования лаунчера вы должны быть авторизованы хотя бы на одной учетной записи. После этого вам придется войти снова.<br><br>Вы уверены, что хотите выйти?"
confirmButton = "Я уверен"
cancelButton = "Отмена"

[js.settings.authAccountPopulate]
username = "Имя пользователя"
uuid = "UUID"
selectAccount = "Выбрать аккаунт"
selectedAccount = "Выбран аккаунт ✓"
logout = "Выйти"

[js.settings.dropinMods]
removeButton = "Удалить"
deleteFailedTitle = "Не удалось удалить<br>мод-добавку {fullName}"
deleteFailedMessage = "Убедитесь, что файл не используется, и повторите попытку."
failedToggleTitle = "Не удалось переключить<br>одну или несколько мод-добавок"
okButton = "ОК"

[js.settings.serverListing]
mainServer = "Основной сервер"

[js.settings.java]
selectedJava = "Выбрано: Java {version} ({vendor})"
invalidSelection = "Неверный выбор"
requiresJava = "Требуется Java {major} x64."
availableOptions = "Доступные опции для Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Предварительный релиз"
stableReleaseTitle = "Стабильный релиз"
releaseNotesFailed = "Не удалось загрузить заметки о релизе."

[js.settings.updates]
newReleaseTitle = "Доступен новый релиз"
newPreReleaseTitle = "Доступен новый предварительный релиз"
downloadingButton = "Загрузка.."
downloadButton = 'Загрузить с GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Закройте лаунчер и запустите dmg для обновления.</span>'
latestVersionTitle = "Вы используете последнюю версию"
checkForUpdatesButton = "Проверить наличие обновлений"
checkingForUpdatesButton = "Проверка наличия обновлений.."

[js.settings.msftLogin]
errorTitle = "Ошибка входа в Microsoft"
errorMessage = "Не удалось аутентифицировать вашу учетную запись Microsoft. Пожалуйста, попробуйте еще раз."
okButton = "ОК"

[js.uibinder.startup]
fatalErrorTitle = "Фатальная ошибка: Невозможно загрузить индекс дистрибуции"
fatalErrorMessage = "Не удалось установить соединение с нашими серверами для загрузки индекса дистрибуции. Нет доступных локальных копий для загрузки. <br><br>Индекс дистрибуции - это важный файл, который предоставляет актуальную информацию о сервере. Лаунчер не может запуститься без него. Убедитесь, что вы подключены к Интернету, и перезапустите приложение."
closeButton = "Закрыть"

[js.uibinder.validateAccount]
failedMessageTitle = "Не удалось обновить авторизацию"
failedMessage = "Не удалось обновить авторизацию для <strong>{account}</strong>. Пожалуйста, выберите другой аккаунт или войдите снова."
failedMessageSelectAnotherAccount = "Не удалось обновить авторизацию для <strong>{account}</strong>. Пожалуйста, войдите снова."
loginButton = "Войти"
selectAnotherAccountButton = ""

[js.uicore.autoUpdate]
checkingForUpdateButton = "Проверка наличия обновлений..."
installNowButton = "Установить сейчас"
checkForUpdatesButton = "Проверить наличие обновлений"

[js.auth.microsoft.error]
noProfileTitle = "Ошибка при входе:<br>Профиль не настроен"
noProfileDesc = "Ваша учетная запись Microsoft еще не настроена в Minecraft. Если у вас возникли проблемы с входом, попробуйте войти через лаунчер Minecraft."
okButton = "ОК"

[uibinder.startup]
fatalErrorTitle = "Фатальная ошибка: Невозможно загрузить индекс дистрибуции"
fatalErrorMessage = "Не удалось установить соединение с нашими серверами для загрузки индекса дистрибуции. Нет доступных локальных копий для загрузки. <br><br>Индекс дистрибуции - это важный файл, который предоставляет актуальную информацию о сервере. Лаунчер не может запуститься без него. Убедитесь, что вы подключены к Интернету, и перезапустите приложение."
closeButton = "Закрыть"

[uibinder.validateAccount]
failedMessageTitle = "Не удалось обновить авторизацию"
failedMessage = "Не удалось обновить авторизацию для <strong>{account}</strong>. Пожалуйста, выберите другой аккаунт или войдите снова."
failedMessageSelectAnotherAccount = "Не удалось обновить авторизацию для <strong>{account}</strong>. Пожалуйста, войдите снова."
loginButton = "Войти"
selectAnotherAccountButton = ""

[uicore.autoUpdate]
checkingForUpdateButton = "Проверка наличия обновлений..."
installNowButton = "Установить сейчас"
checkForUpdatesButton = "Проверить наличие обновлений"

[auth.microsoft.error]
noProfileTitle = "Ошибка при входе:<br>Профиль не настроен"
noProfileDesc = "Ваша учетная запись Microsoft еще не настроена в Minecraft. Если у вас возникли проблемы с входом, попробуйте войти через лаунчер Minecraft."
noXboxAccountTitle = "Ошибка при входе:<br>Отсутствует учетная запись Xbox"
noXboxAccountDesc = "У вашей учетной записи Microsoft нет ассоциированной учетной записи Xbox."
xblBannedTitle = "Ошибка при входе:<br>Служба Xbox Live недоступна"
xblBannedDesc = "Ваша учетная запись Microsoft принадлежит к стране, где служба Xbox Live недоступна или запрещена."
under18Title = "Ошибка при входе:<br>Требуется родительское разрешение"
under18Desc = "Учетные записи пользователей младше 18 лет должны быть добавлены в Семью взрослым."
unknownTitle = "Неизвестная ошибка при входе"
unknownDesc = "Произошла неизвестная ошибка. Пожалуйста, обратитесь к консоли для получения дополнительной информации."

[auth.mojang.error]
methodNotAllowedTitle = "Внутренняя ошибка:<br>Метод не разрешен"
methodNotAllowedDesc = "Метод не разрешен. Пожалуйста, сообщите об этой ошибке."
notFoundTitle = "Внутренняя ошибка:<br>Не найдено"
notFoundDesc = "Не найдена конечная точка аутентификации. Пожалуйста, сообщите об этой проблеме."
accountMigratedTitle = "Ошибка при входе:<br>Учетная запись мигрирована"
accountMigratedDesc = "Вы пытаетесь войти с мигрированной учетной записью. Попробуйте войти снова, используя адрес электронной почты учетной записи в качестве имени пользователя."
invalidCredentialsTitle = "Ошибка при входе:<br>Неверные учетные данные"
invalidCredentialsDesc = "Введенный вами адрес электронной почты или пароль неверны. Пожалуйста, попробуйте снова."
tooManyAttemptsTitle = "Ошибка при входе:<br>Слишком много попыток"
tooManyAttemptsDesc = "С этой учетной записью было слишком много попыток входа в последнее время. Пожалуйста, попробуйте еще раз позже."
invalidTokenTitle = "Ошибка при входе:<br>Неверный токен"
invalidTokenDesc = "Предоставленный вами токен доступа недействителен."
tokenHasProfileTitle = "Ошибка при входе:<br>Профиль уже присутствует в токене"
tokenHasProfileDesc = "Токен доступа уже имеет присвоенный профиль. Выбор профилей еще не реализован."
credentialsMissingTitle = "Ошибка при входе:<br>Отсутствуют учетные данные"
credentialsMissingDesc = "Имя пользователя/пароль не отправлены или пароль составляет менее 3 символов."
invalidSaltVersionTitle = "Ошибка при входе:<br>Неверная версия соли"
invalidSaltVersionDesc = "Неверная версия соли."
unsupportedMediaTypeTitle = "Внутренняя ошибка:<br>Неподдерживаемый тип медиа"
unsupportedMediaTypeDesc = "Неподдерживаемый тип медиа. Пожалуйста, сообщите об этой ошибке."
accountGoneTitle = "Ошибка при входе:<br>Учетная запись мигрирована"
accountGoneDesc = "Учетная запись была мигрирована на учетную запись Microsoft. Пожалуйста, выполните вход с помощью Microsoft."
unreachableTitle = "Ошибка при входе:<br>Недоступно"
unreachableDesc = "Невозможно подключиться к серверам аутентификации. Убедитесь, что они включены, и у вас есть подключение к Интернету."
gameNotPurchasedTitle = "Ошибка при входе:<br>Игра не приобретена"
gameNotPurchasedDesc = "Учетная запись, с которой вы пытаетесь войти, не приобрела копию Minecraft. Вы можете приобрести копию на <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Неизвестная ошибка при входе"
unknownErrorDesc = "Произошла неизвестная ошибка. Пожалуйста, обратитесь к консоли для получения дополнительной информации."
